### ISSUE TITLE
✨[Feature Request] Add more optional folders that can be synced

### ISSUE THREAD

**Issue by User4716** [enjarai/shared-resources#18]
Here are a few folders that I think would be nice if we had the option to sync them:

- "skins" folder (Used by this mod: https://www.curseforge.com/minecraft/mc-mods/skin-swapper)
- "replay_recordings" (Used by this mod: https://www.replaymod.com/)
- "essential" (Used by this mod: https://essential.gg/en/)

**Comment by enjarai** [comment]
Support for Skin Swapper and Replaymod is definitely possible, I'll look into adding it. 

Essential however makes things a little more difficult due to it being closed source. Not being able to view the source code of a mod makes it very hard for me to find the right place to inject to change the directory, so I won't be adding support for it for now.

**Comment by enjarai** [comment]
Compatibility has been added for ReplayMod and SkinShuffle (a more modern alternative to Skin Swapper (https://modrinth.com/mod/skinshuffle)) as of 1.6.0.

**Comment by User4716** [comment]
Can you add compatibility for Skin Swapper a swell? 😉🤔
I could switch to the alternative but I feel like it would be just easier to stick with the mod I currently have, of course you don't have to do it, but if the folder is named "skins" for both of the mods, I don't see why not add support for SkinSwapper

**Comment by enjarai** [comment]
I'll take a look. I have to make mixin injections into each mod I support to change the part where they resolve their config path, so it's not really directory-based.
