### ISSUE TITLE
✨[Feature Request] Add an option to choose what config files to sync

### ISSUE THREAD

**Issue by User4716** [enjarai/shared-resources#21]
It would be neat if we could choose what global config files we want to use for each modpack separately.

First of all this feature would add a simple GUI where we can see all the config files that are in the global folder, and from there we can select the ones that we want to use on the modpack that we are currently in 👍

**Comment by enjarai** [comment]
This is actually quite difficult to impossible to implement. The way this mod currently handles config syncing is by overriding the base path Fabric loader provides for mods to use as a config directory. It is however fully up to specific mods to decide what to do with it. Due to this, it's not really possible to single out one specific mod to give it different config directory.

The config syncing is more of a catch-all solution when specific compat isnt available.
