### ISSUE TITLE
Screenshot and server support, or custom folder support?

### ISSUE THREAD

**Issue by RNanB** [enjarai/shared-resources#3]
Really cool mod! Would it be possible to add servers.dat and screenshot folder support in the future, so all screenshots go into the same folder? Or even better, a way to select custom folders to be shared, so I could also share stuff like Bobby, Amecs, and Litematica files

**Comment by enjarai** [comment]
I hadn't thought of servers.dat and screenshots yet, but I agree it'd be great to have them. I'll work on adding support for those.

Sadly its not feasable to add support for any arbitrary directory, due to the differing ways different mods interact with files. I will however add compat on a case by case basis when possible. What mods do you think could benefit from compat aside from the ones you mention?

**Comment by enjarai** [comment]
Screenshots, servers and litematica compat implemented in 1.1.0. Compat for other mods is underway, closing for now.
